In [40]:
import cupy
import random as rnd

In [41]:
def print_str(a,b):
    print(str(a),b)

class Point(object):
        
    _registry={}
        
    def __init__(self ,num_globul ,coords):
        self._registry[num_globul] = {'coords' : coords}
        self.coords = coords
        self.num_globul = num_globul
        
    def add_coords(self,coords):
        self.coords.append(coords)
            
    @classmethod 
    def remove_point(self ,num_globul):
        self._registry.pop(num_globul)

rand_final=[]
random_list =[]
max=5
field_test = cupy.zeros((max+2,max+2))
list_for_check_calculate = cupy.array([-1, 0, 1])

In [42]:
for x_rand in range(max):
        for y_rand in range(max):
            random_list.append([x_rand+1,y_rand+1])
print_str(random_list,'random_list')

[[1, 1], [1, 2], [1, 3], [1, 4], [1, 5], [2, 1], [2, 2], [2, 3], [2, 4], [2, 5], [3, 1], [3, 2], [3, 3], [3, 4], [3, 5], [4, 1], [4, 2], [4, 3], [4, 4], [4, 5], [5, 1], [5, 2], [5, 3], [5, 4], [5, 5]] random_list


In [43]:
check_list = []
for x in list_for_check_calculate:
    for y in list_for_check_calculate:
        check_list.append([x,y])
check_list.remove([0,0])     
check_list=cupy.array(check_list)
print_str(check_list, 'check_list')

[[-1 -1]
 [-1  0]
 [-1  1]
 [ 0 -1]
 [ 0  1]
 [ 1 -1]
 [ 1  0]
 [ 1  1]] check_list


In [44]:
point_1=Point(1 ,[[divmod(max,2)[0],divmod(max,2)[0]]])

In [45]:
new_particle = rnd.choice(random_list)
rand_final.append(new_particle)
random_list.remove(new_particle)
point_2=Point(2 ,[[new_particle[0],new_particle[1]]])
print(Point._registry)

{1: {'coords': [[2, 2]]}, 2: {'coords': [[2, 3]]}}


In [46]:
for k,v in Point._registry.items():
    print(v)#координата частицы
    print_str(k,'номер частицы')
    print(v['coords'])
    for i in v['coords']:
        field_test[i[0]][i[1]]=k

print(field_test,'field_test')  

{'coords': [[2, 2]]}
1 номер частицы
[[2, 2]]
{'coords': [[2, 3]]}
2 номер частицы
[[2, 3]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]] field_test


In [47]:
print(check_list)
for y in check_list:
    a=y[0]
    b=y[1]
    print([a,b])

[[-1 -1]
 [-1  0]
 [-1  1]
 [ 0 -1]
 [ 0  1]
 [ 1 -1]
 [ 1  0]
 [ 1  1]]
[array(-1), array(-1)]
[array(-1), array(0)]
[array(-1), array(1)]
[array(0), array(-1)]
[array(0), array(1)]
[array(1), array(-1)]
[array(1), array(0)]
[array(1), array(1)]


In [48]:
print_str(Point._registry,'до проверки')
list_for_delete=[]
    #========= Проверка соседей (начало) =========
    
for coord_check in check_list:
    x=coord_check[0]
    y=coord_check[1]  
    x_2 = point_2.coords[0][0]
    y_2 = point_2.coords[0][1]
    print(Point._registry)
    if (field_test[x_2+x][y_2+y]!=0)==True:
        print('test finished')
        point_1.add_coords(point_2.coords[0])
        print('add_coords')
        

        field_test[x_2][y_2]=1
Point.remove_point(point_2.num_globul)                    
print_str(Point._registry,'после удаления')   

{1: {'coords': [[2, 2]]}, 2: {'coords': [[2, 3]]}} до проверки
{1: {'coords': [[2, 2]]}, 2: {'coords': [[2, 3]]}}
{1: {'coords': [[2, 2]]}, 2: {'coords': [[2, 3]]}}
{1: {'coords': [[2, 2]]}, 2: {'coords': [[2, 3]]}}
{1: {'coords': [[2, 2]]}, 2: {'coords': [[2, 3]]}}
test finished
add_coords
{1: {'coords': [[2, 2], [2, 3]]}, 2: {'coords': [[2, 3]]}}
{1: {'coords': [[2, 2], [2, 3]]}, 2: {'coords': [[2, 3]]}}
{1: {'coords': [[2, 2], [2, 3]]}, 2: {'coords': [[2, 3]]}}
{1: {'coords': [[2, 2], [2, 3]]}, 2: {'coords': [[2, 3]]}}
{1: {'coords': [[2, 2], [2, 3]]}} после удаления


In [49]:
print(field_test)
x_move = point_2.coords[0][0]
y_move = point_2.coords[0][1]
coord_moving = point_2.coords[0]
        
crit_mix_max=0
stop_signal=0
check_list_moving = check_list[:]
     
print('test_1')
while (crit_mix_max==0 and stop_signal==0)==True:
    step_rnd = rnd.choices(check_list_moving)
    for_sum_coord=cupy.array(step_rnd[0])
    print_str(for_sum_coord,' for_sum_coord')
    not_use=1
                # check_list_moving.remove(step_rnd[0])
    new_coord=cupy.array(coord_moving)
    print_str(new_coord,' new_coord')
            
    if step_rnd==[]:
        new_coord=coord_moving
        stop_signal=1
        break
                
    refresh_value=[]
            # print_str(i,' i')
    t=new_coord+for_sum_coord
                # print_str(t,' t')
    refresh_value.append(t.tolist())
    print_str(refresh_value,' refresh_value')
    if ((t[0]<1 or t[1]<1
        or t[0]>max or t[1]>max))==True:
                    not_use+=1
                        # print(check_list_moving)
                        # print(step_rnd)
                            
    if (not_use==1)==True:
                    
        field_test[x_move][y_move]=0
                    
        field_test[refresh_value[0][0]][refresh_value[0][1]]=2
                    
                    # print(str(refresh_value), ' refresh_value')
        crit_mix_max=1
                    
        point_2.coords= refresh_value
                    # print_str(v['coords'],'changed_point')
        break
else:
    print('расчет окончен')
print(field_test)
print_str(len(check_list),'- осталось свободных вариантов')

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
test_1
[0 1]  for_sum_coord
[2 3]  new_coord
[[2, 4]]  refresh_value
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
8 - осталось свободных вариантов
